/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jarego_jayatana_basic_GMainLoop */

#ifndef _Included_com_jarego_jayatana_basic_GMainLoop
#define _Included_com_jarego_jayatana_basic_GMainLoop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jarego_jayatana_basic_GMainLoop
 * Method:    installGMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GMainLoop_installGMainLoop
  (JNIEnv *, jclass);

/*
 * Class:     com_jarego_jayatana_basic_GMainLoop
 * Method:    uninstallGMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GMainLoop_uninstallGMainLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
